---
name: main

on:
  push: # All branches and tags

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}

jobs:
  job:
    permissions: { contents: write }
    uses: dmotte/misc/.github/workflows/cicd-with-script.yml@main
    with: { path: scripts/cicd/rust-app.sh }
